[[redirects]]
  from = "/docs/getting-started/installation"
  to = "/docs/cloud/okteto-cli"
  status = 301
  
[[redirects]]
  from = "/*"
  to = "/docs/404.html"
  status = 404

[build]
  functions = "netlify/functions"