[[redirects]]
  from = "/*"
  to = "/docs/404.html"
  status = 404

[build]
  functions = "netlify/functions"

name = "Check for Broken Markdown links"

[on.pull_request]
branches = [ "master" ]

[[on.schedule]]
cron = "0 0 * * 1"

[jobs.markdown-link-check]
runs-on = "ubuntu-latest"

  [[jobs.markdown-link-check.steps]]
  uses = "actions/checkout@master"

  [[jobs.markdown-link-check.steps]]
  uses = "gaurav-nelson/github-action-markdown-link-check@v1"

    [jobs.markdown-link-check.steps.with]
    use-quiet-mode = "yes"
    use-verbose-mode = "yes"
    config-file = ".mlc_config.json"
    file-extension = ".mdx"
